### PR TITLE
Row colors added for any number of styles for font and background

### PR DESCRIPTION
**Pull request by patfranciso**
I made an enhancement by adding Alternating Row colors for any number of styles for font and background.
trex
trex01
trex02
trex03

Please accept my contribution in this Pull request.
Regards

### CODE REVIEW

**Comment by djm** [comment]
@patfranciso Thanks for the PR, sorry that I totally missed it.

It looks like I need to get the CI build sorted before we can ensure a clean merge.

**Comment by patfranciso** [comment]
No problem

**Comment by djm** [comment]
@patfranciso

Thank you very much for this; it'll be in the next release.

Also thanks to @samhamilton for fixing the CI so we can get these moving easily.

**Comment by patfranciso** [comment]
Thanks @djm for accepting the PR

**Comment by djm** [comment]
@patfranciso [Published](https://hex.pm/packages/table_rex/4.0.0) v3.2.0 and v4.0.0 (dropped support for older Elixir versions). Thanks again.

**Pull request merged**
