### PR TITLE
Support displaying empty rows #48

### LINKED ISSUE #48: Support displaying empty rows
I'm displaying results coming from a database (`"select * ..."` more or less) but when the selection is empty, since it has no rows, TableRex cannot display it:

```
** (TableRex.Error) Table must have at least one row before being rendered
    (table_rex 3.1.1) lib/table_rex.ex:28: TableRex.quick_render!/3
```

It would be more consistent to display an empty table, that is just the header but no rows.

### PR DESCRIPTION
**Pull request by inquisitev**
Closes #48
Adding support for empty rows

### CODE REVIEW

**Comment by djm** [comment]
Thanks @inquisitev; sorry for the wait - CI being out of action made it take longer than usual. This will go out in the next release and I'll update the contributors file.

**Comment by djm** [comment]
@inquisitev [Published](https://hex.pm/packages/table_rex/4.0.0) v3.2.0 and v4.0.0 (drops support for older Elixir versions). Thanks again.

**Comment by inquisitev** [comment]
> @inquisitev [Published](https://hex.pm/packages/table_rex/4.0.0) v3.2.0 and v4.0.0 (drops support for older Elixir versions). Thanks again.

Absolutely, happy to help:)

This was a fun little task to dip my toe into elixir / open source contribution so thanks for the opportunity!

**Comment by djm** [comment]
Nice! Welcome to the community, it's a real good one.

**Pull request merged**
