### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by lowks**
Simplify `.travis.yml`

### CODE REVIEW

**Comment by djm** [comment]
Thanks for your edit. Can I ask what the advantages of this would be? All I currently see is a loss of explicitness.

**Comment by lowks** [comment]
Since it's the default, I thought it would be better to simplify it, if ever a more concise or elaborate command is needed then it can be added back.

**Comment by djm** [comment]
Thanks for the contribution but I don't agree in this case, it's much easier for me to see what it's doing at a glance this way - without having to crawl through their docs looking for a default.

Closing as wontfix.

**Comment by lowks** [comment]
Yeah it's okay

**Pull request closed without merging**
